apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: healthcare-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: healthcare-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
