apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: healthcare-chatbot
type: Opaque
data:
  # Base64 encoded Google API key
  google-api-key: QUl6YVN5Qm1zcER4clRnNTFVLWtSS1JDWEVtVnY1bjNCa2k4SFh3
